version: '3.5'

services:
  gitlab-runner1:
    image: flaviostutz/gitlab-runner
    environment:
      - GITLAB_URL=http://gitlab/
      - REGISTRATION_TOKEN=jPhhnDq7aRygyrMRzJ9e
      - DESCRIPTION=Runner1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner1-etc:/etc/gitlab-runner
      - gitlab-runner1-home:/home/gitlab-runner
    deploy:
      labels:
        traefik.frontend.rule: Host:gitlab-runner1.${CLUSTER_DOMAIN}
        traefik.port: "80"
        traefik.docker.network: traefik-net
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M
    networks:
      - traefik-net

  #Gitlab server is here just for testing purposes of Gitlab Runner
  gitlab:
    image: gitlab/gitlab-ce:10.8.3-ce.0
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.${CLUSTER_DOMAIN}'
    deploy:
      labels:
        traefik.frontend.rule: Host:gitlab.${CLUSTER_DOMAIN}
        traefik.port: "80"
        traefik.docker.network: traefik-net
      replicas: 1
    networks:
      - traefik-net
    volumes:
      - gitlab_etc:/etc/gitlab
      - gitlab_opt:/var/opt/gitlab
      - gitlab_log:/var/log/gitlab

networks:
  traefik-net:
    external: true

volumes:
  gitlab-runner1-etc:
  gitlab-runner1-home:
  gitlab_etc:
  gitlab_opt:
  gitlab_log:
